---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: print out the hostname of target
    command: hostname

  - name: ensure nginx is installed
    become: true
    become_method: sudo
    command: apt install nginx

  - name: update the apt package index i.e. apt update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt upgrade
    apt: upgrade=yes
